### ISSUE TITLE
Improve instructions

### ISSUE THREAD

**Issue by seirdotexe** [007revad/Synology_Cleanup_Coredumps#1]
Nice project, but I have an improvement. Because you recommend to download the file and put it on your NAS, and if someone were to use Task Scheduler, you'd have to manually update. Instead, you could do this:
![image](https://github.com/007revad/Synology_Cleanup_Coredumps/assets/80536518/314b3ca6-b348-455a-aff1-ce24d906e46f)

**Comment by 007revad** [comment]
Thanks

**Comment by 007revad** [comment]
I had to use:
`curl -sLJO "https://github.com/007revad/Synology_Cleanup_Coredumps/raw/main/syno_clean_coredumps.sh" && chmod 700 $HOME/syno_clean_coredumps.sh && $HOME/syno_clean_coredumps.sh`

**Comment by seirdotexe** [comment]
I modified my screenshot. It works for me.

**Comment by 007revad** [comment]
Do you have the task set to run as root?

**Comment by seirdotexe** [comment]
Yes

**Comment by 007revad** [comment]
Okay, I tested it a bit more and the only change I need is to include curl's -L option.
`bash <(curl -sL https://github.com/007revad/Synology_Cleanup_Coredumps/raw/main/syno_clean_coredumps.sh)`

It might depend on how close to the github server a person is whether they need curl to follow redirects or not. 

BTW I just noticed how horrible the script's output is if there's no core dump files found.
